<?php
    $_helper = Mage::helper('mageacf');
    $_acfs = $_helper->getACFJson();
?>
<div class="hidden-phone acf-container">
    <div class="title">
        <a class="btn-clear fr" href="#"><?php echo $this->__('Clear'); ?></a>
        <span><?php echo $this->__('Color'); ?></span>
    </div>
    <div class="filters">
        
    </div>
</div>

<script type="text/javascript">
    var acfJson = jQuery.parseJSON('<?php echo addslashes($_acfs); ?>');
    var storeview = '<?php echo Mage::app()->getStore()->getId(); ?>';
    var colorId = <?php echo $_helper->getColorAttributeId(); ?>;
    var layerColors = jQuery.parseJSON('<?php echo addslashes($_helper->getCurrentLayerState()); ?>');
    var isAvailableColorOnly = <?php echo $_helper->isAvailableColorOnly(); ?>
</script>