<?php
    $_acfs = Mage::helper('mageacf')->getACFJson();
?>
<div class="hidden-phone acf-container">
    <div class="title">
        <a class="btn-clear fr" href="#"><?php echo $this->__('Clear'); ?></a>
        <span><?php echo $this->__('Color'); ?></span>
    </div>
    <div class="filters">
        
    </div>
</div>

<script type="text/javascript">
    var acfJson = jQuery.parseJSON('<?php echo addslashes($_acfs); ?>');
    var storeview = '<?php echo Mage::app()->getStore()->getId(); ?>';
    var colorId = <?php echo Mage::helper('mageacf')->getColorAttributeId(); ?>;
</script>